name: Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
    - uses: azure/docker-login@v1
      with:
        login-server: leapcodeproject.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t leapcodeproject.azurecr.io/myapp:${{ github.sha }}
        docker push leapcodeproject.azurecr.io/myapp:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'leapapplication'
        images: 'leapcodeproject.azurecr.io/myapp:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
